versatum/blog/urls.py
import views as blog
from django.conf.urls import url

urlpatterns = [
    url(r'^$', blog.articles, name="articles"),
    url(r'^(\d+)/$', blog.article, name="article"),
]

versatum/home/urls.py
import views as home
from django.conf.urls import url

urlpatterns = [
    url(r'^$', home.homepage, name="homepage"),
    url(r'^help/$', home.help, name="help"),
    url(r'^about/$', home.about, name="about"),
    url(r'^community/$', home.community, name="community"),
]

versatum/project/urls.py
import views as home
from django.conf.urls import url

urlpatterns = [
    url(r'^$', home.home, name="home"),
]

versatum/versatum/urls.py
import views
from utils import HandleError

from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns

handler400 = HandleError(status_code=400)
handler403 = HandleError(status_code=403)
handler404 = HandleError(status_code=404)
handler500 = HandleError(status_code=500)

urlpatterns = [
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$', views.files, name='home-files'),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name="register"),
    url(r'^confirm/(?P<string>[\w\W]+)/$', views.confirm, name="confirm"),
    url(r'^', include("home.urls", namespace="home")),
    url(r'^project/', include("project.urls", namespace="project")),
    url(r'^blog/', include("blog.urls", namespace="blog")),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

versatum/templates/base.html
{% load i18n static %}

<html lang="{{ get_current_language  }}">
<head>
    <meta charset="utf-8"></meta>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- ===================== FAVICONS ======================== -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/favicons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
    <meta name="msapplication-TileImage" content="{% static 'img/favicons/ms-icon-144x144.png' %}">
    <link rel="manifest" href="{% static 'img/favicons/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <!-- ==================== CSS ============================= -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ===================== Font ============================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <link href="{% static 'font/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- ===================================================== -->
    <title> {% block title %} Versatum - {{ title }} {% endblock title %} </title>

    {% block head %}
    {% endblock head %}

</head>
<body>
    {% block nav  %}
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#id-navbar-collapse" aria-expanded="false">
                    <span class="sr-only"> {% trans 'Menu' %} </span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span classs="icon-bar"></span>
                </button>
                <a style="padding:0;"  title="{% trans 'Início' %}"  class="navbar-brand" href="{% url 'home:homepage' %}">
                    <img src="{% static "img/logo-extended.png" %}" alt="Versatum" />
                </a>
            </div>
            <div class="collapse navbar-collapse" id="id-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item active">
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <p class="navbar-text">{% trans "Hello" %}, {{ request.user.first_name }}</p>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}"> <i class="fa fa-user-times"> </i> {% trans 'Logout' %}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}"> <i class="fa fa-user"> </i> {% trans 'Login' %} </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">  {% trans 'Register' %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock %}
{% block body %}
{% block outdoor %}
<section class="jumbotron orange">
    <div class="container">
        <h1 class="jumbotron-heading">{% block page-title %} Versatum {% endblock page-title %} </h1>
        <p class="normal">
            {% block page-description %}
                {% blocktrans %} We are a non-profit organization with the goal of creating new technologies to solve human problems {% endblocktrans %}
            {% endblock page-description %}
        </p>
    </div>
</section>
{% endblock  %}
{% block main %}
<main class="content">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-2">
                <ul class="nav nav-pills nav-stacked">
                    <li  role="presentation" ><a href="{% url 'blog:articles' %}"> {% trans 'Blog' %} </a></li>
                    <li  role="presentation" ><a href="{% url 'project:home' %}"> {% trans 'Projects' %} </a></li>
                    <li  role="presentation" ><a href="{% url 'home:about' %}"> {% trans 'About us' %} </a></li>
                    <li  role="presentation" ><a href="{% url 'home:help' %}"> {% trans 'Support us' %} </a></li>
                    <!--
                    <li  role="presentation" ><a href="{% url 'home:community' %}"> {% trans 'Community' %} </a></li>
                    -->
                </ul>
            </div>
            <div class="col-sm-12 col-md-9 col-lg-10 ">
                {% block content %}
                {% endblock content  %}
            </div>
        </div>
    </div>
</main>
{% endblock main %}
{% endblock body%}
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h4> {% trans 'Support us' %} </h4>
                <ul class="simple">
                    <li><a href="{% url 'home:help' %}#helpout"> <i class="fa fa-link"> </i> {% trans 'Help out' %} </a></li>
                    <!--<li><a href="{% url 'home:help' %}#donations"> <i class="fa fa-link"> </i> {% trans 'Donations' %} </a></li>
                    <li><a href="{% url 'home:help' %}#dev"> <i class="fa fa-link"> </i> {% trans 'Development' %} </a></li>
                    <li><a href="{% url 'home:help' %}#disclose"> <i class="fa fa-link"> </i> {% trans 'Promote us' %} </a></li>-->
                </ul>
                <h4> {% trans 'Contact us' %} </h4>
                <ul class="simple">
                    <li>
                        <i class="fa fa-envelope"> </i>
                        {% trans 'E-mail' %}
                        <a href="mailto:contact@versatum.org">
                            contact@versatum.org
                         </a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-12 col-md-6">
                <h4> {% trans 'Sociais Networks' %} </h4>
                <ul class="simple">
                    <li><a href="https://www.facebook.com/versatum/" target="_blank"> <i class="fa fa-facebook-square"> </i> Facebook </a></li>
                    <li><a href="https://github.com/Versatum" target="_blank"> <i class="fa fa-github"> </i> Github </a></li>
                    <li><a href="https://www.linkedin.com/company/versatum/" target="_blank"> <i class="fa fa-linkedin"> </i> Linkedin </a></li>
                </ul>
                <h4> {% trans 'Languages' %} </h4>
                <ul class="simple">
                    <li><a href="/pt-br/"> <span class="flag brazil"> </span> {% trans 'Portuguese' %} </a></li>
                    <li><a href="/es/"> <span class="flag spain"> </span> {% trans 'Spanish' %} </a></li>
                    <li><a href="/en/"> <span class="flag usa"> </span> {% trans 'English' %} </a></li>
                </ul>
            </div>
            <div class="col-sm-12">
                <hr>
                <address>
                    <strong> Versatum Org </strong>
                    <p> {% trans 'All right reserved' %}® </p>
                </address>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-3.1.1.slim.min.js' %}"><\/script>')</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script>
    if(typeof($.fn.modal) === 'undefined') {
        document.write('<script src="{% static 'js/bootstrap.min.js' %}"><\/script>');
    }
</script>
<script>
    $(document).ready(function() {
        var $this;
        $("li[role=presentation] a").each(function(index) {
            $this = $(this);
            if ($this.attr('href') === window.location.pathname){
                $this.parent().addClass('active');
            }
        });
    });
</script>

{% block js-script %}

{% endblock js-script %}

</body>
</html>

versatum/templates/error.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
Versatum - {{ titulo }}
{% endblock title %}

{% block body %}
<main class="content">
    <div class="container">
        <div class="jumbotron orange">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h1 class="jumbotron-heading"> {% trans 'Erro' %} {{ status  }}  </h1>
                    <p class="normal">
                        {{ mensagem }}
                    </p>
                </div>
                <div class="col-sm-12 col-md-6">
                    <img alt="Error" src="{% static 'img/error-image-mini.png' %}">
                </div>
            </div>
        </div>
    </div>
    <br>
</div>
{% endblock %}

versatum/templates/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    Versatum - {% trans 'Login' %}
{% endblock %}

{% block outdoor %}
<section class="jumbotron">
    <div class="container">
        <h1 class="jumbotron-heading">{% trans 'Login' %}</h1>
        <p class="normal">
            {% block page-description %}
            {% blocktrans %} We are a non-profit organization with the goal of creating new technologies to solve human problems  {% endblocktrans %}
            {% endblock page-description %}
        </p>
    </div>
</section>
{% endblock  %}


{% block main %}
    <main  class="content">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="{% url 'home:homepage' %}"> Home </a></li>
                <li class="active"> {% trans 'Login' %} </li>
            </ol>

            <div class="row">
                <div class="col-sm-12 col-md-6  col-md-offset-3">
                    {% if request.user.is_authenticated %}
                        <div class="alert alert-success">
                            <p> {% trans 'You already logged in' %} </p>
                        </div>
                    {% else %}
                    <form class="well" action="?next={{ request.path }}" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-primary btn-block"> {% trans 'Send' %}  </button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

versatum/templates/register.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    Versatum - {% trans 'Login' %}
{% endblock %}

{% block outdoor %}
<section class="jumbotron">
    <div class="container">
        <h1 class="jumbotron-heading">{% trans 'Register' %}</h1>
        <p class="normal">
            {% block page-description %}
            {% blocktrans %} We are a non-profit organization with the goal of creating new technologies to solve human problems  {% endblocktrans %}
            {% endblock page-description %}
        </p>
    </div>
</section>
{% endblock  %}


{% block main %}
    <main  class="content">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="{% url 'home:homepage' %}"> Home </a></li>
                <li class="active"> {% trans 'Resgister' %} </li>
            </ol>

            <div class="row">
                <div class="col-sm-12 col-md-6  col-md-offset-3">
                    {% if user %}
                        <div class="alert alert-success">
                            <h4> {% blocktrans %}  Your information was saved! {% endblocktrans %} </h4>
                            <p>
                                {% blocktrans %} We send a e-mail to you confirm then {% endblocktrans %} <br>
                            <a href="{% url 'home:homepage' %}" >  {% blocktrans %} Back to Home {% endblocktrans %} </a>
                        </p>
                        </div>
                    {% else %}
                    <form class="well" action="?next={{ request.path }}" method="POST">
                        {{ form }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-block"> {% trans 'Send' %}  </button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}