versatum/blog/urls.py
import views as blog
from django.conf.urls import url

urlpatterns = [
    url(r'^$', blog.articles, name="articles"),
    url(r'^(\d+)/$', blog.article, name="article"),
]

versatum/home/urls.py
import views as home
from django.conf.urls import url

urlpatterns = [
    url(r'^$', home.homepage, name="homepage"),
    url(r'^help/$', home.help, name="help"),
    url(r'^about/$', home.about, name="about"),
    url(r'^community/$', home.community, name="community"),
]

versatum/versatum/urls.py
import views
from utils import HandleError

from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns

handler400 = HandleError(status_code=400)
handler403 = HandleError(status_code=403)
handler404 = HandleError(status_code=404)
handler500 = HandleError(status_code=500)

urlpatterns = [
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$', views.files, name='home-files'),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name="register"),
    url(r'^confirm/(?P<string>[\w\W]+)/$', views.confirm, name="confirm"),
    url(r'^', include("home.urls", namespace="home")),
    url(r'^project/', include("project.urls", namespace="project")),
    url(r'^blog/', include("blog.urls", namespace="blog")),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

versatum/blog/models.py
from __future__ import unicode_literals

from utils import rename_image

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Author(models.Model):
    user = models.OneToOneField(
        User,
        verbose_name=_("User"),
    )
    picture = models.ImageField(
        upload_to=rename_image,
    )
    about = models.TextField(
        verbose_name=_("About"),
    )

    def __unicode__(self):
        return self.user.get_full_name()


class Tag(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=100,
    )
    description = models.TextField(
        verbose_name=_("Description"),
        null=True, blank=True
    )

    def __unicode__(self):
        return self.name


class Article(models.Model):
    author = models.ForeignKey(
        Author,
        verbose_name=_("Author"),
    )
    title = models.CharField(
        verbose_name=_("Title"),
        max_length=128,
    )
    cover = models.ImageField(
        upload_to=rename_image,
    )
    description = models.TextField(
        verbose_name=_("Description"),
    )
    text = models.TextField(
        verbose_name=_("Text"),
    )
    tags = models.ManyToManyField(
        Tag,
        verbose_name=_("Tags"),
    )
    publication_date = models.DateTimeField(
        verbose_name=_("Publication date"),
    )
    created = models.DateTimeField(
        verbose_name=_("Created"),
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        verbose_name=_("Modified"),
        auto_now=True,
    )

    def __unicode__(self):
        return "Article: {0} - {1}".format(
            self.title,
            self.author,
        )


class ArticleImage(models.Model):
    article = models.ForeignKey(
        Article,
        verbose_name=_("Article"),
    )
    image = models.ImageField(
        upload_to=rename_image,
    )
    label = models.CharField(
        verbose_name=_("Label"),
        max_length=100,
        null=True,
        blank=True,
    )

    def __unicode__(self):
        return "Article Image: {0} - {1}".format(
            self.article,
            self.lebel,
        )

versatum/blog/views.py
# coding: UTF-8

from models import Article

from django.shortcuts import render
from django.shortcuts import get_object_or_404

def articles(request):
    articles = Article.objects.all()
    data = dict(
        articles=articles,
    )
    return render(request, 'blog_home.html', data)


def article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    data = dict(
        article=article,
    )
    return render(request, 'blog_article.html', data)

versatum/blog/templates/blog_article.html
{% extends "blog_base.html" %}
{% load i18n static %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home:homepage' %}"> Home </a></li>
        <li><a href="{% url 'blog:articles' %}"> {% trans 'Articles' %} </a></li>
        <li class="active"> {{ article.title }} </li>
    </ol>
     <div class="row">
         <div class="col-lg-12 ">
             <h2 class="text-center"> {{ article.title }} </h2>
             <br style="margin: 2rem 0;">
         </div>
         <br>
         <div  class="col-lg-offset-8 col-lg-4">
         <p> {{ article.publication_date  }} </p>
        </div>
        <br>
        <div  class="col-lg-12">
             <div class="media">
              <div class="media-left">
                <a href="#">
                  <img class="media-object" src="{{ article.author.picture.url }}" width="90" alt="{{ article.author.name }}">
                </a>
              </div>
              <div class="media-body">
                <h4 class="media-heading"> {% trans  'by' %} {{ article.author }} </h4>
                    {{ article.author.about|truncatechars_html:140 }}
              </div>
            </div>
            </div>
             <img style="width: 100%;margin: 2rem 0;" class="img-rounded" src="{{ article.cover.url }}" alt="{% trans 'cover' %}"/>
             <hr>
             <div>
                 <p class="lead text-justfy"> {{ article.description }}  </p>
             </div>
             <article>
                 {{ article.text|safe }}
             </article>
              <hr>
              <p> {% trans 'Tags' %}:
                  {% for tag in article.tags.all %}
                      <a href="#" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="{{ tag.description }}">
                         {{ tag }}
                         <i class="fa fa-tags" aria-hidden="true"></i>
                     </a>
                  {% endfor %}
              </p>
          </div>
      </div>
{% endblock %}

{% block js-script %}
<script>
$(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

{% endblock %}

versatum/blog/templates/blog_base.html
{% extends "base.html" %}
{% load i18n static %}


{% block title %}
    Versatum - {% trans 'Blog' %}
{% endblock %}


{% block outdoor %}
    <section class="jumbotron wine">
      <div class="container">
        <h1 class="jumbotron-heading"> {% trans "Blog" %}  </h1>
        <p class="normal">
            {% block page-description %}
                {% blocktrans %} We are a non-profit organization with the goal of creating new technologies to solve human problems {% endblocktrans %}
            {% endblock page-description %}
        </p>
      </div>
    </section>
{% endblock outdoor %}

versatum/blog/templates/blog_home.html
{% extends "blog_base.html" %}
{% load i18n static %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home:homepage' %}"> Home </a></li>
        <li class="active"> {% trans 'Articles' %} </li>
    </ol>
    {% for article in articles %}
     <div class="row">
         <div class="col-lg-12 ">
             <h2 class="text-center"> {{ article.title }} </h2>
         </div>
         <div class="col-lg-7">
             <p> {% trans  'by' %} <a href="#" data-toggle="modal" data-target="#aboutAuthor-{{ article.author.pk }}"> {{ article.author }}  </a> <p>
         </div>
         <div  class="col-lg-5">
             <p> {{ article.publication_date  }} </p>
        </div>
        <div  class="col-lg-12">
             <p class="lead text-justfy"> {{ article.description }}  </p>
        </div>
        <div class="col-lg-4">
             <img style="width: 100%" class="img-rounded" src="{{ article.cover.url }}" alt="{% trans 'cover' %}"/>
         </div>
         <div class="col-lg-8">
             {{ article.text|safe|truncatechars_html:400 }}
             <a href="{% url 'blog:article' article.pk %}"> {% trans 'read more' %} </a>
          </div>
      </div>
      <hr>
      <div class="modal fade" id="aboutAuthor-{{ article.author.pk }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"> {{ article.author.user.get_full_name }} </h4>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="col-lg-4">
                <img src="{{ article.author.picture.url }}" style="width: 100%;">
            </div>
            <div class="col-lg-8">
                <p>
                    {{ article.author.about }}
                </p>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
    {% empty %}
        <div class="alert alert-danger">
            <p> {% trans 'No Articles found' %} : ( </p>
        </div>
    {% endfor %}

{% endblock %}